### ISSUE TITLE
"Document is not defined" error on Next.JS when Implementing the library 

### ISSUE THREAD

**Issue by ReyMga** [crisp-im/crisp-sdk-web#10]
I installed the crisp-sdk-web in a Next.js project, but I am getting an error: "document is not defined". 

![image](https://user-images.githubusercontent.com/65356965/211922776-d22b0c4f-52ca-48a2-a220-db86fd66d0f4.png)

Note: With a common react project (create-react-app) it works OK.

**Comment by ReyMga** [comment]
It works for next js, it was a configuration error from my side. 
Thank you!

**Comment by baptistejamin** [comment]
Hi, our agents are offline at the moment. Please leave a message and we will get back to you as soon as possible.

**Comment by baptistejamin** [comment]
Hello!

How did you solve the problem?

**Comment by loiclouvet** [comment]
> Hello!
> 
> How did you solve the problem?

@baptistejamin Might be related to server side rendering for Nextjs. Crisp has to be loaded client side only. A solution could be to put the `configure` or `load` method inside a `useEffect`.
