### ISSUE TITLE
Crisp found shims of native JavaScript methods.

### ISSUE THREAD

**Issue by tgensol** [crisp-im/crisp-sdk-web#15]
Hello la team,

Depuis qu'on a implémenté Sentry coté Front, on a des warning : https://github.com/getsentry/sentry-javascript/issues/2130

On a depuis des clients qui nous disent nous avoir écrit, mais aucune trace de leurs messages chez Crisp. Ils nous appellent pour comprendre pourquoi ils n'ont pas de réponses. Est-ce que vous pensez que ça peut être lié ? Nous n'avons pas réussi à reproduire l'issue pour obtenir plus d'informations

Merci

**Comment by eliottvincent** [comment]
Hello Thibaut! À priori Sentry override des fonctionnalités natives JS, sur lesquelles Crisp repose. Cela peut impacter le fonctionnement de la chatbox. Il faut voir avec eux ou forker la lib Sentry pour enlever ces overrides.

**Comment by tgensol** [comment]
@eliottvincent  https://github.com/getsentry/sentry-javascript/issues/2130#issuecomment-1495855450, Sentry est quand même très utilisé..., ne serait-ce pas à votre lib d'essayer de régler ça ?

**Comment by baptistejamin** [comment]
Sentry override le comportement natif de fonctions JS. Crisp, passe derrière et se retrouve avec des fonctions modifiées par une autre lib.

Si la lib (ici Sentry) fait bien son travail, alors ca ne cause pas de problème.

Nous avons ajouté ce message car dans de très nombreux cas, des Framework modifient très salement les fonctions JS, et on se retrouve avec des comportements de fonctions totalement différents. Par exemple parseInt qui au lieu de retourner un entier retourne une string...

Les Shims  d'objets natifs JS est quelque chose qui nous a fait perdre énormément de temps en support, et pour éviter tout problème on a préféré ajouter ce warning.

**Comment by tgensol** [comment]
hello @baptistejamin merci pour la réponse rapide et très claire,

Mon point est qu'il semble que depuis que l'on a implémenté Sentry sur notre front, des clients se plaignent de messages fantômes, qui n'apparaissent pas sur le dashboard de Crisp. Si le problème persiste, cela nous amènera à une réflexion sur l'outil en lui-même, à notre grand regret... En attendant, j'ai demandé à mes équipes opérationnelles de me remonter rapidement quand cela se produit pour vous donner le maximum d'informations

**Comment by baptistejamin** [comment]
Pas sur que ceci soit lié à Sentry. C'est quoi ce que tu appelles des messages fantômes?

Le must serait de voir ça ensemble sur notre support, pourquoi pas avoir un screen recording.
