### ISSUE TITLE
Carousel message type mismatch between docs & typings

### ISSUE THREAD

**Issue by anisabboud** [crisp-im/crisp-sdk-web#16]
SDK docs for carousel message use `"description": "...string..."`, while `message.ts` typings define `description: boolean`.
Also, typings include a required `label` field, while the docs example is missing that field. Which is the correct code to use?

https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/npm/#show-a-carousel-message
![image](https://user-images.githubusercontent.com/5672108/233101219-620ec715-6380-40aa-a519-aa6423ddb5e8.png)

https://github.com/crisp-im/crisp-sdk-web/blob/master/src/message.ts#L42
![image](https://user-images.githubusercontent.com/5672108/233102072-b0da6e6e-046a-4277-a575-09716d11fd8d.png)

**Comment by baptistejamin** [comment]
This is clearly a bug with the TS definition. Let me fix this

**Comment by baptistejamin** [comment]
v1.0.17 is now release :)

**Comment by baptistejamin** [comment]
Updated :)
