### ISSUE TITLE
Impossible de changer de tokenId sans recharger la page

### ISSUE THREAD

**Issue by SimonCooperl** [crisp-im/crisp-sdk-web#19]
Bonjour,

J'intègre le sdk crisp dans une app mobile (techno angular). Je veux pouvoir changer le tokenId sans recharger l'appli et j'ai l'impression que ce n'est pas possible. 

J'ai essayé de réécrire la config avec `Crisp.setTokenId(newToken);` ou  `Crisp.configure(key, { tokenId: newToken });` sans succès. J'ai également essayé la commande de reset ` $crisp.push(['do', 'session:reset']);` sans résultat. J'ai l'impression qu'il n'y a pas moyen de reload Crisp sans recharger la page.

Un idée ?
Simon

**Comment by eliottvincent** [comment]
Bonjour Simon! Pouvez-vous essayer avec la dernière version du SDK? N'hésitez pas à venir sur notre support pour voir votre implémentation en détails: https://crisp.chat
