### ISSUE TITLE
The operand of a 'delete' operator must be optional.

### ISSUE THREAD

**Issue by dev-smart-ui** [crisp-im/crisp-sdk-web#22]
Hi my build on vercel does not work 
./node_modules/crisp-sdk-web/src/index.ts:209:16
Type error: The operand of a 'delete' operator must be optional.
        window.CRISP_TOKEN_ID = tokenId;
      } else {
        delete window.CRISP_TOKEN_ID;
             ^
   }
   }

./node_modules/crisp-sdk-web/src/index.ts:4:3
Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

  2 | 
  3 | export {
> 4 |   AnimationMessage,
    |   ^
  5 |   AudioMessage,
  6 |   FileMessage,
  7 |   PickerMessage,
- info Linting and checking validity of types .

next js 13  , typescript 4.9.3 , node js 18
npm run build 
usage 
import { Crisp } from "crisp-sdk-web";

**Comment by baptistejamin** [comment]
You should skipLibCheck in your ts config Sent from my iPhoneOn 22 Aug 2023, at 10:33, Smart-UI ***@***.***> wrote:﻿
Hi my build on vercel does not work
./node_modules/crisp-sdk-web/src/index.ts:209:16
Type error: The operand of a 'delete' operator must be optional.
window.CRISP_TOKEN_ID = tokenId;
} else {
delete window.CRISP_TOKEN_ID;
^
}
}
next js 13  , typescript 4.9.3 , node js 18
npm run build
usage
import dynamic from "next/dynamic";
import React from "react";
const Crisp = dynamic(
() => import("components/Crisp").then((mod) => mod.CrispChat),
{ssr: false}
);
export const ChatCrisp = () => {
return 
}
