### ISSUE TITLE
Implement Crisp.chat.onChatLoaded() function

### ISSUE THREAD

**Issue by piotrkulpinski** [crisp-im/crisp-sdk-web#23]
Hi,
I'm integrating the Crisp into my React app and I'd love to be able to know when the Crisp chat is fully loaded. 
I'm using the `autoload: false` option and loading Crisp manually via `Crisp.load()` method. 

I'd like to add a UI loader to let users know when the chat is loading. 

I've tried `onChatOpened` and `onChatInitiated` but it does not trigger after first programatic open.

Thanks!

**Comment by eliottvincent** [comment]
You can use the [session loaded callback](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/npm/#session-loaded-callback):

```javascript
Crisp.session.onLoaded((sessionId) => {
  // Executed once the Crisp session is loaded

  console.log(sessionId);
})
```
