### ISSUE TITLE
Resize Crisp widget withtout the SDK

### ISSUE THREAD

**Issue by sabatale** [crisp-im/crisp-sdk-web#24]
Would it be possible to add an option to resize the widget directly from the CDN version? (without including the SDK)

`<script type="text/javascript">window.$crisp = []; window.CRISP_WEBSITE_ID = "uuid"; (function () { d = document; s = d.createElement("script"); s.src = "https://client.crisp.chat/l.js"; s.async = 1; d.getElementsByTagName("head")[0].appendChild(s); })();</script>`

For example, a parameter such `CRISP_WIDGET_SIZE= "sm"`?

**Comment by eliottvincent** [comment]
Hey, this is not possible, you need to use the SDK for that.
