### ISSUE TITLE
session.reset error

### ISSUE THREAD

**Issue by marc-rutkowski** [crisp-im/crisp-sdk-web#28]
`Crisp.session.reset()` triggers an error `window.$crisp.do is not a function`.

The culprit seems to be the following line :
https://github.com/crisp-im/crisp-sdk-web/blob/a30d3c437bbb41d207f929871d767ae6f3582eab/src/session.ts#L25

that should be changed to:
`window.$crisp.push(["do", "session:reset", [reload]]);`

Let me know if I need to open a PR.

**Comment by eliottvincent** [comment]
Hey, thanks for reporting the issue. This is fixed, make sure to update to the latest version (v1.0.25)
