### ISSUE TITLE
Provide API equivalent to push set message:text

### ISSUE THREAD

**Issue by huksley** [crisp-im/crisp-sdk-web#29]
## Bug

How to open a window and prefill a chatbox user text with a value. In JS SDK, it is done by using:

```js
$crisp.push(["set", "message:text", [msg]]);
```

Is there a method equivalent to do that? I was not able to find any. I am using "crisp-sdk-web": "^1.0.21".

## Implementation

Would be great to have something like:

```ts
Crisp.chat.setMessageText(msg)
```

**Comment by eliottvincent** [comment]
Now possible with most recent version:

```javascript
Crisp.message.setMessageText("I have a question");
```

**Comment by huksley** [comment]
Confirmed working @eliottvincent 
Using this code instead of `$crisp.push(["set", "message:text", [msg]]);`

**Comment by baptistejamin** [comment]
Confirmed working with the following code:

```javascript
Crisp.message.setMessageText("I have a question");
```
