### ISSUE TITLE
Get A mirror in vue3

### ISSUE THREAD

**Issue by jashok2** [crisp-im/crisp-sdk-web#5]
index.ts:173 Refused to load the script 'https://client.crisp.chat/l.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

What should I do?

**Comment by baptistejamin** [comment]
I would recommend adjusting your CSP policies as described here: https://docs.crisp.chat/guides/others/whitelisting-our-systems/crisp-domain-names/
