### ISSUE TITLE
Passing options to configure() disables autoload

### ISSUE THREAD

**Issue by jakajancar** [crisp-im/crisp-sdk-web#7]
It is very misleading that passing options to `configure()` (e.g. `locale`, or even an empty `{}`) disables autoload. I suspect most people will assume that whatever option they passed is what broke the widget.

Instead of
```
configure(websiteId: string, options: Options = {autoload : true }) {
```
it should be
```
configure(websiteId: string, options: Options = {}) {
```

and then defaults should be resolved on a per-option basis within the body.

**Comment by baptistejamin** [comment]
Thank you for the report!

Issue got fixed
